### ISSUE TITLE
建议加进度条&网速，多线程下载&上传

### ISSUE THREAD

**Issue by conql** [zaxtyson/LanZouCloud-CMD#1]
刚想做一个控制台版客户端，就发现万能的GitHub已经有了这么棒的项目，感谢开发者。

**Comment by zaxtyson** [comment]
本来是多线程的，不过会莫名其妙出错，总是有一些文件无法上传。单线程上传因为没有限速，也可以跑满带宽，所以就去掉了多线程上传。进度条，emm，是的，我应该加上。

**Comment by zaxtyson** [comment]
新版本已经支持使用回调函数显示上传/下载进度
