### ISSUE TITLE
[建议]登录输入密码时将密码替换为*而不是直接不显示

### ISSUE THREAD

**Issue by AaronFeng753** [zaxtyson/LanZouCloud-CMD#10]
如题, 我理解您的意思是保护用户密码不被别人看到, 但是完全不显示任何输入, 真的给人一种软件出错没接收到输入的感觉, 我在那跟傻子一样敲了半天键盘才发现这软件隐藏密码的方式是直接不显示任何输入

**Comment by ghost** [comment]
Linux系统在命令行界面下输入密码就没有回显，他这个明显是仿Linux的，包括命令关键字等等

**Comment by zaxtyson** [comment]
是的，的确是模仿的  linux 来的，所以没打算回显，反正登录也是登录一次，之后就是 cookie 自动登录。输入密码时注意输入法中英文状态就好~
