### ISSUE TITLE
[作者] 关于分卷文件名格式的意见征集

### ISSUE THREAD

**Issue by zaxtyson** [zaxtyson/LanZouCloud-CMD#12]
目前在分卷文件名这里存在一些问题：

- 如果使用 `.xxx[0-9]+.rar`  作为分卷文件的后缀名，即便 `xxx` 是随机字符串，官方也可以继续封杀。虽然说目前只是简单的加入黑名单，但是以后可能通过正则匹配封杀全部文件，不知道能撑多久。

- 如果将分卷信息使用 base64 之类的算法加密，与文件名混淆到一起，官方就没办法直接封杀，否则很有可能误杀正常用户的文件，但是这样就导致**只有使用本工具的用户才能下载这些文件**，分享给其他人，别人也无法直接解压这些分卷。(早在 `v1.x` 版的时候，没有使用压缩工具，直接进行数据切片，后来为了分享后方便其他人解压，才开始使用 `rar` 进行分卷压缩)

使用随机后缀先撑住，还是放弃其它没有使用本工具的用户? 或者各位有更好的解决方案嘛？😭

**Comment by rachpt** [comment]
直接开放给用户设置，怎么样？
在文件夹描述里面留下 分卷规则说明。

**Comment by srcrs** [comment]
留给用户设置也可以。但我感觉以前那种加密比较好一点。比如说现在这种方式，超过100M的文件会进行分卷，命名也会进行简单加密，事实上也只有使用本工具的用户才能够正确的下载文件并使用，所以简单加密，复杂加密对其它不使用此工具的用户影响并不大。小文件还用以前的方式就可以了，毕竟小文件网页端也是可以上传的。

**Comment by srcrs** [comment]
留给用户设置也可以。但我感觉v1.x那种加密比较好一点。比如说现在这种方式，超过100M的文件会进行分卷，命名也会进行简单加密，事实上也只有使用本工具的用户才能够正确的下载文件并使用，所以简单加密，复杂加密对其它不使用此工具的用户影响并不大。小文件还用以前的方式就可以了，毕竟小文件网页端也是可以上传的。

**Comment by zaxtyson** [comment]
后缀使用 `.xxx[0-9]+.rar`  的好处就是没有使用本工具的用户下载后，rar 解压软件也能识别并解压。如果使用复杂混淆的话(base64加密后缀，然后参杂到文件名中去)，安全性是上去了，但是其它用户没办法解压，即便在 `文件夹描述` 里面留下解密过程，普通用户也很难处理，尤其是分卷比较多的情况下，用户无法判断分卷顺序。

**Comment by srcrs** [comment]
这样啊，我还以为wtf还需要改回part。

**Comment by srcrs** [comment]
那就像你所说的，分卷多了普通用户可能区分不了分卷顺序，估计很多人都没有那个耐心一个个下载吧，倒不如用工具来的简单方便。如果只是几个分卷就另说了。

**Comment by zaxtyson** [comment]
要不先随机后缀用着，实在是挂了再加密混淆😭
