### ISSUE TITLE
回收站闪退

### ISSUE THREAD

**Issue by rachpt** [zaxtyson/LanZouCloud-CMD#14]
这其实是 https://github.com/zaxtyson/LanZouCloud-API 的bug。

当文件名太长而没有显示后缀名时，`_get_right_name` 
https://github.com/zaxtyson/LanZouCloud-API/blob/89f4d3e00d2cbf51cd7e8c64dfad9bf499923b49/lanzou/api.py#L291
```py
fn_list = filename.replace('#', '.').split('.')
suffix, sub_suffix = fn_list[-1], fn_list[-2]
```
list 发生越界错误
IndexError: list index out of range。

https://i.loli.net/2020/02/23/lJXm1S5xRvUPCuo.png
https://i.loli.net/2020/02/23/vJ4QLCgiFPekHuw.png

-----
最后有一个疑问，
https://github.com/zaxtyson/LanZouCloud-CMD/blob/ca82bf47282d1bb411dcbfc4f09566290c66910c/lanzou-cmd.py#L5
`readline` 在windows平台上好像装不上啊，python3.8.1

https://stackoverflow.com/questions/51157443/pythons-readline-module-not-available-for-windows

**Comment by zaxtyson** [comment]
是的， `readline` 模块早在2012年就废弃了，作者把它改名为了 `gnureadline` : https://pypi.org/project/gnureadline/  但是它也不支持 Windows，要在 Windows 上使用 `readline` 其实要安装 `pyreadline`，这个之前没说明😜。回收站我去看看先~

**Comment by zaxtyson** [comment]
`dev` 分支已经修复，https://github.com/zaxtyson/LanZouCloud-API/tree/dev
顺带过了登录时的滑动验证👌
