### ISSUE TITLE
分卷压缩顶不住了

### ISSUE THREAD

**Issue by zaxtyson** [zaxtyson/LanZouCloud-CMD#16]
是的，伙计们，我们又双叒叕被 ban 了(这个项目似乎被官方盯上了😥)
正如 #12  所说，这次是正则匹配，包含 `.xxx[0-9]+.rar` 的文件名全部被限制了
看样子想继续支持普通用户直接解压出大文件是不太可能了。
文件名得搞复杂化，混淆到官方容易误杀的程度。但是这样一来，只能在本程序中才能看到正常的文件名，直接看网盘可能文件名一团糟。而且代码是开源的，这样混淆规则很容易被官方加入限制策略。既要混淆的如同普通文件一般，又要有显著的特点与之区分，这很矛盾。但是放弃普通用户后，我们有了更多选择，比如说回到 #2 之前的方法，这样甚至都不需要 `rar` 支持，文件名可以随意，真正的信息放到其它文件里面。

哦，回到那最初的起点😭

**Comment by shadowfish07** [comment]
哈哈哈哈哈哈，我也在想这个问题，我把文件分包后随机15位乱码+改后缀为.exe，依然有部分文件传不了

**Comment by shadowfish07** [comment]
我试了一下，同名的乱码文件，如果用一个比较小的上传就可以成功，用一个100M的文件就会失败。我猜官方不仅是从命名上ban，一个文件夹里相同大小的文件太多也会被BAN。（一堆的100M太明显了吧）

**Comment by shadowfish07** [comment]
批量上传的结果也可以支持我的结论，从一个文件开始后面所有文件都会上传失败

**Comment by zaxtyson** [comment]
这次麻烦了，看样子我得搞复杂点才行😥

**Comment by zaxtyson** [comment]
现在比较大的 dll 文件也给 ban 了

**Comment by ghost** [comment]
这是我之前关于分卷压缩的思考：https://www.52pojie.cn/thread-1089379-1-1.html

**Comment by ghost** [comment]
那个帖子主要讨论的是文件名的问题。
体积问题我觉得可以用随机数来决定每个分卷的体积。比如1~99MB，让每个分卷都有不同的大小，这样就不会出现一堆100M的问题了。
后缀名问题，可以使用随机后缀名。比如在预先给定的“后缀名白名单列表”中给每个分卷文件都随机添加一个后缀名，下载之后再把添加的多余后缀名直接删除即可。还可以设置一个后缀名黑名单，如果某个后缀名上传失败的次数过多，则从白名单中移除，添加到黑名单中。

**Comment by ghost** [comment]
体积甚至可以设置的更小一点，反正是批量操作，又不用一个一个手动上传。

**Comment by ghost** [comment]
我觉得不使用工具还要上传分享超过100M的大文件是不太现实的

**Comment by ghost** [comment]
关于文件名，还有个办法就是通过一个文本文件记录该目录下的真实文件名和伪装文件名的对应关系，真实文件名所对应的中文字符串随机生成就行了。比如：
```
name.part1.rar 活动此外你都三次.ppt
name.part2.rar 法海德国扫到速度.xls
name.part3.rar 符号嘀咕阿松地扫.doc
```
文件夹下由一个"readme.txt"的文本文件和一堆伪装文件名的分卷文件构成，下载的时候通过对应关系还原出真实文件名称并解压。蓝奏云应该不可能限制这种几kb的txt文件上传吧。

**Comment by zaxtyson** [comment]
是的，目前 API 的策略和您想的差不多: 
- 分卷文件大小在不超过 `max_size` 的情况下波动，可能减少的大小和出现概率按权重计算，使得 80-100M 的文件多一些，但是也可能产生比较小的文件。
- 文件后缀随机，且这些使用这些后缀的文件一般比较大(几十MB的 doc 就很奇怪，可能被杀)
- 分卷文件的文件夹的确是有一个 `readme.txt` ，保险起见这个文件名也是随机的，内容也是 `pickle` 序列化的二进制数据，只能使用 Python 才能读取和解析。
- 普通文件使用 `dll` 后缀也被限制了，官方开始检查文件大小了。这个还在想策略，如果也使用 `readme.txt` 的方式，我怕他把 `readme.txt` 这个名字都封杀了。最重要的是，每一次上传、删除等操作，都要修改这个文件，这个文件经常要删除，上传，可能引来封杀。后缀信息本来想放描述信息里面，但是用户可能自己想设置描述，所以搞一个复杂点的方法加密真实后缀，放文件名里面。
- 为了调用方便， API 还在重构中~
- 再封杀，就要和正常用户同归于尽了😂

**Comment by rachpt** [comment]
文件名使用 readme 还不如直接使用 BASE64加密 文件名？

**Comment by zaxtyson** [comment]
是的，普通的文件我打算用 base64，但是怕官方也按照这个方法去解密，然后 ban 掉。所以仅加密真实后缀，然后按照一些规则混入文件名，这样混淆后文件名应该与正常用户上传的文件名相似，防止正则匹配。加密方式应该要复杂，即便开源，官方也难以实现或者花费很大代价。比如使用 pickle 序列化成 python 特有的格式再 base64。但是考虑到日常使用的格式就那么多，官方还是可以匹配加密后的结果。还挺麻烦的。

**Comment by ghost** [comment]
其实还有一种复杂点的方法，不用readme记录文件名，而是直接把文件名以二进制的方式写进分卷文件的开头或者结尾，上传时的文件名随意生成就行。
但是最后提取的时候会复杂一点，因为文件名长度不同，你要提取的字符串长度就是动态变化的。
这个问题的解决方法可以模仿网络传输的报头，先提取固定长度的报头，然后读取报头中的真实文件名字符串的长度，还原出真实文件名即可。

**Comment by zaxtyson** [comment]
和我想到一块去了，文件格式不支持时，把文件后缀藏到文件里面最安全，再给它随机分配个后缀，一般在文件尾部追加信息一般不影响文件的使用。麻烦的地方就是，除非下载完成，否则我们也不知道格式是啥，网盘也无法正确显示。

**Comment by ghost** [comment]
我认为绝对不能改变原文件，哪怕只有几个字节。
如果写的话我建议写在文件的开头，写在后面的话需要逆向读取。不应该只写后缀，应该把全部的文件名写进去。
下载完成后组合的时候先读取所有文件的报头，把真实文件名和假文件名对应关系还原出来，存一个字典，根据真实文件名的序号排序，最后合并的时候，每个文件都从跳过文件名之后的位置开始读取并写入最终的文件。
字符串和二进制字节的转换可能是最容易出问题的地方，使用不同编码转换后的二进制字节长度不同。
分卷文件只能靠文件夹名称来判断了。

**Comment by zaxtyson** [comment]
目前大文件分段上传的问题已经解决了，分段数据的顺序、真实文件名、文件大小是序列化为二进制后保存在 txt 文件中(这个文件名也随机)。下载时按顺序下载各段写入文件，不需要再本地合并一次。目前代码工作的很好。
现在的问题是，后缀不支持的普通小文件如何伪装？我是打算上传时在文件尾部添加一个 "报头"，下载完成的时候判断一下，如果发现就去掉，并且重命名。

**Comment by zaxtyson** [comment]
“分卷文件只能靠文件夹名称来判断” 这个有危险性，通过描述信息、文件夹名、文件名来判断，官方都可以检查字符串。写入文件内部更加保险，而且还是 python 特有的格式，即便官方能处理，代价也很大。

**Comment by ghost** [comment]
文件名可以保留原来的文件名，只替换分卷编号和后缀部分，这样就知道存的是哪个文件的分卷了。

**Comment by ghost** [comment]
类似于这样
```
name.part1.rar name哈哈哈哈哈.ppt
name.part2.rar name啊啊啊啊啊.xls
name.part3.rar name顶顶顶顶顶.doc
```

**Comment by shadowfish07** [comment]
哈哈哈哈哈哈我用视频分割的方法实现了视频文件的上传，我发现我的视频名称是有规律的：xxx_01,xxx_02但是大小不同，依然能全部上传成功

**Comment by zaxtyson** [comment]
就怕官方找规律😥
`v2.4.0` 已经可以了，目前没发现bug，我已经完全放弃在文件名上做文章了，这回应该稳了
