### ISSUE TITLE
推荐加一个上传文件自动去除密码并返回分享链接的功能

### ISSUE THREAD

**Issue by shadowfish07** [zaxtyson/LanZouCloud-CMD#19]
我是不是有点过分了XD

**Comment by shadowfish07** [comment]
喔，还有，上传文件后原文件夹下会有tmp文件夹，这个得自动删掉吧

**Comment by zaxtyson** [comment]
上传后文件是默认关闭密码的，获取分享链接使用 share 命令即可。关于tmp文件夹，这个实在是疏忽了，其实会自动删除的，昨天为了测试，把这个注释掉了，忘记恢复😂。https://github.com/zaxtyson/LanZouCloud-CMD/blob/a4d96423fb00c80cb15c4dcff7f2bb30fd92e052/lanzou/api/utils.py#L145

**Comment by shadowfish07** [comment]
哈哈哈哈哈好的

**Comment by zaxtyson** [comment]
已经更新，重写打包，恢复了自动删除 tmp 文件夹的功能。已经下载 `v2.4.0` 的 70 多个小伙伴看到这个 Issue 的话，记得重新下载，虽然影响不是很大~
