### ISSUE TITLE
建议文件分片机制使用zip或其他方式

### ISSUE THREAD

**Issue by wll8** [zaxtyson/LanZouCloud-CMD#2]
如果使用后缀，短期看起来比较简单，但是如果lanzou后台可能会根据文件信息判断真实文件类型而失效。

当前的分片机制会产生一个文件夹、多个 .dll 伪装文件、一个 .seed.txt 文件，处理起来成本比较高。

如果用 zip 自己提供的分包机制，这样别人下载后可以自动组包，感觉好处应该大于目前分包机制。

**Comment by zaxtyson** [comment]
是的，但是我觉得大文件压缩要很多时间，但是节约的空间并不是很多，而且蓝奏云上传不限速，就没压缩了。

**Comment by wll8** [comment]
使用【存储】选项，可以不经压缩，直接分卷存储，速度极快，堪比复制。

**Comment by zaxtyson** [comment]
但是这样和没压缩基本上差不多😥

**Comment by zaxtyson** [comment]
新版本中已经改为rar分卷压缩，感谢提议~~
