### ISSUE TITLE
好像大于100mb的文件无法上传 

### ISSUE THREAD

**Issue by GillianJiao** [zaxtyson/LanZouCloud-CMD#20]
刚刚测试了下  小于100mb可以上传  但是用来个200mb的就闪退了

**Comment by shadowfish07** [comment]
纳尼，我刚传了个7G的电影都成功了，美滋滋

**Comment by GillianJiao** [comment]
我一上传就闪退  有没有操作错误啊

**Comment by zaxtyson** [comment]
是 clone 代码运行的吗，exe 应该没问题，跑代码需要 python3.8 支持

**Comment by GillianJiao** [comment]
我是运行的exe 要用py跑吗

**Comment by zaxtyson** [comment]
exe 的话不需要安装python环境，莫非您是 32 位系统，打包是用 64 位Python弄的，不支持 32 位

**Comment by GillianJiao** [comment]
64位的

**Comment by zaxtyson** [comment]
解决了吗？在 cmd 里面运行 lanzou-cmd.exe 看看，崩溃了能看见异常。

**Comment by GillianJiao** [comment]
这几天没玩了  等下来看看
