### ISSUE TITLE
上传功能被限制

### ISSUE THREAD

**Issue by aosoz** [zaxtyson/LanZouCloud-CMD#23]
上传了若干个大文件后无法再上传了。。。。
官方答复：
![捕获](https://user-images.githubusercontent.com/61775959/75856081-946e8900-5e2e-11ea-85bb-e7e49baa53de.PNG)

**Comment by zaxtyson** [comment]
看样子官方放弃技术抵抗，现在开始封号了吗😂，这可真的没办法了
