### ISSUE TITLE
传了几次比较大的文件之后，再传大文件就会闪退了

### ISSUE THREAD

**Issue by shadowfish07** [zaxtyson/LanZouCloud-CMD#24]
建议出一个直接生成tmp文件的选项吧，实在不行就手动上传tmp文件

**Comment by zaxtyson** [comment]
按照 #23 的情况，搞不好是打算封你号了，别搞太猛了，细水长流啊兄弟

**Comment by zaxtyson** [comment]
为了防止一次性将大文件切片浪费时间， tmp 里面的文件是通过生成器产生的，上传完成一个，再从大文件切一块，然后文件名随机，所有文件上传成功了才能生成记录文件。下载的时候根据它指定的顺序下载切片数据，写入一个文件。这样就不用合并的时候再拷贝一次浪费时间。手动上传的话，程序会忽视这块数据，因为没有记录。
