### ISSUE TITLE
上传大于100MB的，不成功

### ISSUE THREAD

**Issue by Jiolt** [zaxtyson/LanZouCloud-CMD#25]
虽然上传显示100%，但找不到文件  
![image](https://user-images.githubusercontent.com/43039952/76297595-080f0b00-62f3-11ea-83bb-a8f86f7c6c29.png)

**Comment by zaxtyson** [comment]
试一下refresh强制刷新，可能是网页端数据没更新。

**Comment by Jiolt** [comment]
强制刷新后还是没有，是不是不能上传大于100MB的了

**Comment by zaxtyson** [comment]
我这边十分正常🤣，也不是文件名的问题。老兄试试重新下载试试，如果还是有问题，不排除账号被照顾的可能。

![](https://upload.cc/i1/2020/03/14/x7yHvi.png)

**Comment by Jiolt** [comment]
看来是被照顾了  ，无法上传大于百兆的

**Comment by zaxtyson** [comment]
参考 #23，或许可以和官方协商一下(/▽＼)
