### ISSUE TITLE
大文件通过分享链接无法下载

### ISSUE THREAD

**Issue by shadowfish07** [zaxtyson/LanZouCloud-CMD#27]
https://www.lanzous.com/b015ai7he
这个链接，下载后会闪退，download目录下生成`C_Primer_Plus_第六版\C_Primer_Plus_第六版.pdf`，但是只有1KB。
不过登陆后直接下载文件夹是可以正常下载的。
还有，上传文件的时候如果文件有非法字符，会闪退，建议加一个判断，避免闪退了。

**Comment by zaxtyson** [comment]
通过 URL 下载时，默认检测文件的尾部 512 字节，看看能不能提取到文件信息。恰好记录文件也是可以被反序列化的，而且我用了同一个 key 表示文件名，结果把记录文件当误判成了普通文件，开始截断文件尾部 512 字节，但是记录文件根本没有这么大就崩了。

你这个记录文件反序列化得到的文件名列表中，有一个文件和网盘的文件名不一致，有点奇怪欸。
这会导致该文件夹被判断为普通文件夹，然后只下载数据，不合并。

上传小文件是真的没有去除非法字符，感谢~

![](https://upload.cc/i1/2020/03/24/LpRYxI.png)

![](https://upload.cc/i1/2020/03/24/iPR4p1.png)

**Comment by shadowfish07** [comment]
我又传了本书上去，下载还是闪退，好像还是同样的情况欸😂
https://www.lanzous.com/b015ak2nc

**Comment by zaxtyson** [comment]
我推到 dev 分支了，试试看，但是你的文件名似乎有点奇怪，记录文件和网盘文件名不一致。我之前上传了一本书没问题。 https://www.lanzous.com/b0f1enmqh

**Comment by zaxtyson** [comment]
蓝奏云上传时会把你临时文件名中 `3P` 这个词去掉了,可能是什么诡异的文件名检测机制
3p版第_m六f_r9sidfreu_PClPzo.pdf -> 版第_m六f_r9sidfreu_PClPzo.pdf 
f_prfP中rCm_版e3P5ui版ll_第sdu6文.tar -> f_prfP中rCm_版e5ui版ll_第sdu6文.tar

但是我这边上传好像没有问题😅

**Comment by shadowfish07** [comment]
噢，是这样，我的客户端是没修复tmp文件夹BUG的2.4.0版本，我去下载安装了最新的2.4.0，就可以正常上传下载了

**Comment by zaxtyson** [comment]
但是的确暴露出来几个bug👍
