### ISSUE TITLE
大佬！可以支持断点续传嘛

### ISSUE THREAD

**Issue by TullyMonster** [zaxtyson/LanZouCloud-CMD#29]
> LanZouCloud-CMD.exe
1. 有时候大文件传输会不明原因地中断而无法继续操作，只能退出命令行。
2. 分块上传的文件，将统一集合在一个文件夹。在 ls 列出大文件文件夹列表时，可以注明大文件的大小嘛？
3. 不知道以后可否支持断点续传哦
4. 用于暂存分割文件的 `tmp` 文件夹可以命名为 `<大文件名>tmp<启动上传的开始时间>` 嘛，防止因上传失败，重试时，出现文件混合的现象
5. `bye` 命令退出 cmd 无效
6. 可以同时提交多个文件的上传和下载任务吗，依次执行

**Comment by rachpt** [comment]
下载 断点续传的话，可以这样做
https://github.com/rachpt/lanzou-gui/commit/6269e23aa267b94d7b3f58bf67cbf94333385c4c

**Comment by zaxtyson** [comment]
1. 上传有时候的确挺迷惑的，可能是官方在那边有什么检测机制。
2. 大文件的文件夹描述为 `BigFile`，这个只是给用户的提醒，程序不使用它进行判断（太简单的方式容易被官方杀掉）。判断一个文件夹是否为"大文件"，要读取文件夹下的文件列表，然后下载"记录文件"，校验通过才能判断文件夹为"大文件"，这个过程中要获取文件列表，提取直链，下载，开销比较大。如果想 ls 直接显示大小的话，要遍历当前文件夹下的所有子文件夹，如果文件夹多了就要很长时间，所有没有直接显示了。进入这个文件夹再 ls 可以看到数据大小，自己估算一下差不多了。
3. 断点续传之后可以加上。因为下载失败还是不常见，主要是上传问题，所以一直没关注这个。😄感谢 @rachpt
> 下载 断点续传的话，可以这样做
> [rachpt/lanzou-gui@6269e23](https://github.com/rachpt/lanzou-gui/commit/6269e23aa267b94d7b3f58bf67cbf94333385c4c)
4. 和官方的斗争经验告诉我们，对文件名动手脚很容易被检测出来，所以不敢让文件名的太有规律。每次上传，文件名，大小，格式，都是随机的，上传完成之前谁也不知道会产生些什么东西，所以才安全。不过这里的确有改进空间。
5. 这个是有点问题，直接运行 `.py` 文件可以退出了，打包成 exe 后就退不出来了
6. 多个上传会出问题，多个下载可以后面加上。
