### ISSUE TITLE
大于100MB文件上传后全部乱码

### ISSUE THREAD

**Issue by jzcangshu** [zaxtyson/LanZouCloud-CMD#30]
【win10 64】我上传了一个大于100MB的.exe自解压压缩包，上传过程一切正常，上传完毕后使用网页版查看此文件夹中的所有文件名都是乱码状态，重新下载下来后也无法正常解压缩等。软件自动上传内附的TXT文件文件名和文件内容也都是乱码。求解决，阿里嘎多

**Comment by shadowfish07** [comment]
乱码是正常的，这里是分包上传，下载要用down命令下载。自己从蓝奏上下载没用

**Comment by jzcangshu** [comment]
好的谢谢，明白了。但是刚刚打开想重试的时候又出现了
error：检测更新时发生异常，请问怎么解决，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shadowfish07"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月29日(星期天) 晚上7:12
收件人:&nbsp;"zaxtyson/LanZouCloud-CMD"<LanZouCloud-CMD@noreply.github.com&gt;;
抄送:&nbsp;" ๛🙃۶"<2454139183@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zaxtyson/LanZouCloud-CMD] 大于100MB文件上传后全部乱码 (#30)





 
乱码是正常的，这里是分包上传，下载要用down命令下载。自己从蓝奏上下载没用

**Comment by shadowfish07** [comment]
正常，随便按个键应该就能进去了

**Comment by jzcangshu** [comment]
了解了，感谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shadowfish07"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月29日(星期天) 晚上7:16
收件人:&nbsp;"zaxtyson/LanZouCloud-CMD"<LanZouCloud-CMD@noreply.github.com&gt;;
抄送:&nbsp;" ๛🙃۶"<2454139183@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zaxtyson/LanZouCloud-CMD] 大于100MB文件上传后全部乱码 (#30)





 
正常，随便按个键应该就能进去了
