### ISSUE TITLE
希望开发一个独立的解压程序

### ISSUE THREAD

**Issue by jzcangshu** [zaxtyson/LanZouCloud-CMD#33]
如果只有自己使用的话本工具还是非常好用的，但是如果想要给别人分享就会非常麻烦。所以作者大大能不能新增一个在上传文件的时候自动上传一个类似“点我解压”的exe，自动合并下载文件，可以独立运行的那种，会方便很多，谢谢！

**Comment by zaxtyson** [comment]
虽然可以做到啦(￣▽￣)"。但是我觉得，一个大文件里面包括这么多文件，别人也不会这么耐心一个一个手动下载，再使用 `点我解压.exe` 这样的工具合并数据吧。直接使用 CMD 或者 GUI 程序，你只要分享文件夹的链接给别人，一个链接一步到位，岂不美哉？

**Comment by lvhao866** [comment]
那这样是不是别人也需要下载cmd，python

**Comment by zaxtyson** [comment]
linux 都是有 python 环境的，clone 项目就能用，Windows版的是打包好了的，不用安装 Python，下载安装就行了。
