### ISSUE TITLE
 2.4.3版本下载不了任何文件直接报错，请教

### ISSUE THREAD

**Issue by iori8421** [zaxtyson/LanZouCloud-CMD#35]
LanZouCloud > down https://www.lanzous.com/b015ai7he
LanZouCloud > jobs
----------------------------------------------------------------------------------------------------
[0] Status: Error    | Process:   0.00% | Download: https://www.lanzous.com/b015ai7he
----------------------------------------------------------------------------------------------------
LanZouCloud >                                                                                                                               

不知道是什么问题 ，直接下载自己网盘的文件也是这样

**Comment by iori8421** [comment]
LanZouCloud > down https://www.lanzous.com/iazp4gf
LanZouCloud > jobs
----------------------------------------------------------------------------------------------------
[0] Status: Error    | Process:   0.00% | Download: https://www.lanzous.com/b015ai7he
[1] Status: Error    | Process:   0.00% | Download: https://www.lanzous.com/iazp4gf
----------------------------------------------------------------------------------------------------
LanZouCloud >

**Comment by zaxtyson** [comment]
`[]` 里面的是 PID 号，使用 `jobs PID` 查看错误日志，可能是提取码错误，文件取消，网络异常等等原因

**Comment by zaxtyson** [comment]
`https://www.lanzous.com/b015ai7he` 已经失效了，`https://www.lanzous.com/iazp4gf` 我这里可以正常下载(￣▽￣)"

![](https://upload.cc/i1/2020/04/05/gKkIXA.png)

**Comment by iori8421** [comment]
LanZouCloud > down https://www.lanzous.com/iazp4gf
LanZouCloud > jobs
----------------------------------------------------------------------------------------------------
[0] Status: Error    | Process:   0.00% | Download: https://www.lanzous.com/iazp4gf
----------------------------------------------------------------------------------------------------
LanZouCloud > jobs 0
[0] Status: Error    | Process:   0.00% | Download: https://www.lanzous.com/iazp4gf
Error Messages:
文件下载失败: 提取码错误 -> https://www.lanzous.com/iazp4gf
LanZouCloud >                                                                                                                             

提示我要提取码，但是我看你下载是不要提取码的

**Comment by zaxtyson** [comment]
这就很神奇了啊，之前的版本能下载吗

**Comment by iori8421** [comment]
一直没有成功过。自从发现这个软件开始

**Comment by zaxtyson** [comment]
可能是其它软件导致的冲突或者系统环境的问题，比如开了 VPN 之类有时会导致下载失败。之前有人也出现了问题，后来查明是其它软件导致的，https://github.com/zaxtyson/LanZouCloud-CMD/issues/5#issue-548573792
如果手边有其它设备，或者虚拟机之类的，可以试试。

**Comment by iori8421** [comment]
系统是重新安装的，vpn也关闭测试过还是不行。我换台电脑试试看。还有可以增加一个log看看原因吗？

**Comment by zaxtyson** [comment]
release 版是关闭了 debug 的，如果您想看具体的 log, 请 clone 这个项目，然后修改 https://github.com/zaxtyson/LanZouCloud-CMD/blob/30f08ff1fdd4b06d79e02fa9af0b1ac1ff1d08df/lanzou/api/utils.py#L17
为 `logging.DEBUG` ,运行时会在控制台输出具体的日志。
环境为 Python3.8+，依赖: requests, requests_toolbelt

**Comment by iori8421** [comment]
好郁闷 换了台电脑还是不行。
LanZouCloud > down https://www.lanzous.com/iazp4gf
LanZouCloud > jobs
----------------------------------------------------------------------------------------------------
[0] Status: [1;31mError   [0m | Process:   0.00% | Download: https://www.lanzous.com/iazp4gf
----------------------------------------------------------------------------------------------------
LanZouCloud > jobs 0
[0] Status: [1;31mError   [0m | Process:   0.00% | Download: https://www.lanzous.com/iazp4gf
Error Messages:
文件下载失败: 提取码错误 -> https://www.lanzous.com/iazp4gf
LanZouCloud >

**Comment by zaxtyson** [comment]
我这边也开始提取码错误了，api直接调用没问题，应该是cmd的问题，我再查一下

**Comment by iori8421** [comment]
> release 版是关闭了 debug 的，如果您想看具体的 log, 请 clone 这个项目，然后修改
> 
> https://github.com/zaxtyson/LanZouCloud-CMD/blob/30f08ff1fdd4b06d79e02fa9af0b1ac1ff1d08df/lanzou/api/utils.py#L17
> 
> 
> 为 `logging.DEBUG` ,运行时会在控制台输出具体的日志。
> 环境为 Python3.8+，依赖: requests, requests_toolbelt

配置完后提示需要readline模块 但是这个模块安装报错。看来我是搞不定了。只能指望老板了。

**Comment by zaxtyson** [comment]
问题根源应该是 https://github.com/zaxtyson/LanZouCloud-API/issues/16#issue-593704486
近期蓝奏云官方页面总是在变化，一些链接处理时会出错，这个 Issue 还没有完全处理完成。

刚刚把修复推送到了 dev 分支，clone 下来试试，已经可以正常下载，，版本是 `v2.4.4`
Windows 上面需要安装 pyreadline，参考
https://github.com/zaxtyson/LanZouCloud-CMD/issues/5#issuecomment-582718662
https://github.com/zaxtyson/LanZouCloud-CMD/issues/14#issuecomment-590166417

**Comment by iori8421** [comment]
LanZouCloud > down https://www.lanzous.com/iazp4gf
LanZouCloud > jobs
----------------------------------------------------------------------------------------------------
[0] Status: Finished | Process: 100.00% | Download: https://www.lanzous.com/iazp4gf
----------------------------------------------------------------------------------------------------
LanZouCloud > jobs 0
[0] Status: Finished | Process: 100.00% | Download: https://www.lanzous.com/iazp4gf
Error Messages:
LanZouCloud >     


2.4.4 测试成功

**Comment by iori8421** [comment]
2.4.3的报错信息

LanZouCloud > down https://www.lanzous.com/iazp4gf
任务已完成, PID 0, 重新下载吗?(y)y
LanZouCloud > 2020-04-05 15:16:52 [line:871] down_file_by_url DEBUG - File direct url info: DirectUrlInfo(code=2, name='', durl='')

**Comment by zaxtyson** [comment]
哈哈，那就好。😁

**Comment by zaxtyson** [comment]
API 的问题正在跟进中，还在等那个VIP老哥提交测试数据😁。等稳定了再发布 2.4.4 的 release，您可以拿  dev 版凑合用着先。

**Comment by rachpt** [comment]
这行有问题了吧？
https://github.com/zaxtyson/LanZouCloud-API/blob/805eedb135bd8dde44b8b2d4796cafa0a203a366/lanzou/api/utils.py#L30
注释无法全部删除，sign 得到 "df"
![批注 2020-04-05 183741](https://user-images.githubusercontent.com/25758867/78472571-92208700-776c-11ea-8ee6-2cf6d06e4b88.png)

```py
return re.sub(r'<!--.+?-->|\s*//\s*.+', '', html)
```

**Comment by zaxtyson** [comment]
是的，蓝奏云的 js 突然多了注释，2.4.4 的 api 已经改了，但是 vip 的 url 还没处理完，所以就没push上来。(感觉官网真的是很随意啊－_－，生产环境的代码三天两头改一改，跟玩似的)
https://github.com/zaxtyson/LanZouCloud-CMD/blob/36abb8985614b7966f28066f5b90a8de23f078a5/lanzou/api/utils.py#L39
