### ISSUE TITLE
upload完之后用ls命令还是看不到刚刚上传的文件

### ISSUE THREAD

**Issue by ylcz2014** [zaxtyson/LanZouCloud-CMD#37]
上传完之后，在网页端已经可以看到刚刚上传的文件了，但是cmd刷不出来，要关闭再打开一次才行。2.4.3版本

**Comment by zaxtyson** [comment]
refresh 命令刷新一下，因为是后台的子线程在上传，没办法实时刷新。每次进入新的目录，会访问一次网页端，相当于刷新一次。refresh 命令就是用来强制刷新的。如果不使用 refresh，可以切换一个目录再切回来就刷新了。

**Comment by ylcz2014** [comment]
refresh后可以了
