### ISSUE TITLE
能否让在Python 3.7以上版本也能运行？

### ISSUE THREAD

**Issue by DoveBoy** [zaxtyson/LanZouCloud-CMD#38]
安卓手机，已经安装了Python环境，目前能下载的app只有Python3.7的环境，非常想让这个LanZouCloud-CMD能在安装手机上运行，开发者大大能否考虑一下让这个也能在Python3.7环境下能运行？

**Comment by zaxtyson** [comment]
因为用了 Python3.8 的 `:=` 运算符，所以低于 3.8 会报语法错误。
https://github.com/zaxtyson/LanZouCloud-CMD/blob/b5fd0f0e58c3e1a01a2d0ca8ce65c2232d846c3b/lanzou/cmder/cmder.py#L276

你可以  fork 一份，把用到 `:=` 的地方修改一下就行，比如上面的例子。
```
file = self._file_list.find_by_name(arg)
elif file:
```

只有 `cmder.py` 和 `recovery.py` 用了这个运算符
