### ISSUE TITLE
能不能添加一个分卷上传后自动自动删除的功能呢？

### ISSUE THREAD

**Issue by ghost** [zaxtyson/LanZouCloud-CMD#39]
不自动删除感觉有点占空间，手动删除又麻烦（狗头）
手动删除也可以的吧（滑稽）

**Comment by zaxtyson** [comment]
完全上传完成后，会自动删除全部临时文件的，只是删除时间问题，不如一次性删掉，或许应该把这个临时文件夹藏起来（滑稽）

**Comment by ghost** [comment]
但是一次性占用空间啊，看着空间慢慢被填满很不快活的（small狗头）

**Comment by ghost** [comment]
如果可以加一个默认文件提取码设置就好了。就是如果设置了这个属性，就会在上传的时候自动把文件（文件夹）的提取码改成设置值（只是在上传的时候修改）（big and big and big狗头）

**Comment by zaxtyson** [comment]
好吧，下个版本再加上这些功能，没出 bug 就不更新，最近更新挺频繁的。

PS: 为什么你要一直盯着文件夹，看着空间慢慢被填满啊，去喝杯茶，看看番不好咩，放到后台不用管它的啦

![](https://upload.cc/i1/2020/04/08/MjLvan.png)

**Comment by fengyin2020** [comment]
最近才发现这么个神器，老哥强！给老哥star！！
