### ISSUE TITLE
down命令执行不了

### ISSUE THREAD

**Issue by ShaneLee-9** [zaxtyson/LanZouCloud-CMD#4]
down命令下载文件和文件夹都没反应，其他功能正常

**Comment by zaxtyson** [comment]
期末了，有点忙，寒假再修复吧😭

**Comment by rachpt** [comment]
因为 sign 前面多了几行注释，re匹配到了注释，所以无法得到直接下载链接。
https://imgchr.com/i/Q5wUFx

可以这样修改：
https://github.com/rachpt/lanzou-gui/blob/659b74a7783de28d684ce8438cc879d720b3369f/lanzou.py#L293

**Comment by zaxtyson** [comment]
问题全部修复😁
