### ISSUE TITLE
无法用python调用

### ISSUE THREAD

**Issue by lvhao866** [zaxtyson/LanZouCloud-CMD#40]
使用python调用时显示user.dat文件无法找到。

**Comment by zaxtyson** [comment]
请在 user.dat 同级目录下调用，或者修改这一行
https://github.com/zaxtyson/LanZouCloud-CMD/blob/b5fd0f0e58c3e1a01a2d0ca8ce65c2232d846c3b/lanzou/cmder/config.py#L9
使用绝对路径肯定是没有问题的，相对路径要看你的项目结构了。

**Comment by lvhao866** [comment]
下载时一直报错error。链接或者文件都不行。
[0] Status: Error    | Process:   0.00% | Download: LanZouCloud/钢梁桥.7z

**Comment by zaxtyson** [comment]
之前是蓝奏云的链接规则变了，在v2.4.4版本修复了~
