### ISSUE TITLE
上传文件（无论是否为大文件）会发生文件格式被改变的情况，如.jpg文件被改成.ppt或.flac格式的文件

### ISSUE THREAD

**Issue by honestdw** [zaxtyson/LanZouCloud-CMD#41]
上传文件（无论是否为大文件）会发生文件格式被改变的情况，如.jpg文件被改成.ppt或.flac格式的文件，大文件上传时还是会在文件名中增加了_mrdir,有时候单纯的文件被强制变成了文件夹类型，如镜像文件，望改善！

**Comment by zaxtyson** [comment]
- 单个文件过大时会被拆分成小文件，上传后是一个文件夹
- 官方不支持的格式，比如 jpg 会被随机改后缀，下载后会自动改回来
- 无意中添加的 `mkdir` 应该在 `v2.4.4` 去掉了才对 emmm

**Comment by honestdw** [comment]
感谢回复，我之前传了一个qcow2格式的镜像文件被上传成文件夹，这样的文件夹下载下来还会恢复成原来的文件么？如果不能的话好像镜像就损坏了，而且好像文件夹名称好像是带了mkdir的，v2.4.4的

**Comment by zaxtyson** [comment]
下载后会文件名会自动恢复的，文件数据一个字节也不会变。如果下载途中碰到了奇怪的事件导致下载后文件 hash 变化了，可以重新下载一次。mkdir这个就emmm，我去看看，应该没问题才对~ 可以先使用 rename 命令改一下，这个文件夹名没什么意义的，下载的时候自动恢复不看这个的。

**Comment by zaxtyson** [comment]
mkdir 的问题似乎是打包的时候把 2.4.3 的 api 导入了😂 直接 clone 下来运行是没问题的
