### ISSUE TITLE
down出现无法下载现象

### ISSUE THREAD

**Issue by scyibin** [zaxtyson/LanZouCloud-CMD#42]
有测试，不管是大文件，还是小文件，用jobs查看后台，都显示Error错误；上传没有问题。

**Comment by rachpt** [comment]
因为 蓝奏链接不是 www 开头的了，
https://github.com/zaxtyson/LanZouCloud-CMD/blob/b5fd0f0e58c3e1a01a2d0ca8ce65c2232d846c3b/lanzou/api/utils.py#L78
和
https://github.com/zaxtyson/LanZouCloud-CMD/blob/b5fd0f0e58c3e1a01a2d0ca8ce65c2232d846c3b/lanzou/api/utils.py#L94
都匹配不到了，自然没有后续的下载了。

**Comment by rachpt** [comment]
因为 蓝奏分享链接不是 www 开头的了，
https://github.com/zaxtyson/LanZouCloud-CMD/blob/b5fd0f0e58c3e1a01a2d0ca8ce65c2232d846c3b/lanzou/api/utils.py#L78
和
https://github.com/zaxtyson/LanZouCloud-CMD/blob/b5fd0f0e58c3e1a01a2d0ca8ce65c2232d846c3b/lanzou/api/utils.py#L94
都匹配不到了，自然没有后续的下载了。

**Comment by rachpt** [comment]
因为 蓝奏分享链接不是 www 开头的了，
https://github.com/zaxtyson/LanZouCloud-CMD/blob/b5fd0f0e58c3e1a01a2d0ca8ce65c2232d846c3b/lanzou/api/utils.py#L78
和
https://github.com/zaxtyson/LanZouCloud-CMD/blob/b5fd0f0e58c3e1a01a2d0ca8ce65c2232d846c3b/lanzou/api/utils.py#L94
都匹配不到了，自然没有后续的下载了。

**Comment by lvhao866** [comment]
文件名下载或者链接下载都失效了。

**Comment by zaxtyson** [comment]
哦，我的圣母玛利亚，不知道官方整个个性化域名要做什么。
