### ISSUE TITLE
建议取消上传大文件功能

### ISSUE THREAD

**Issue by ghost** [zaxtyson/LanZouCloud-CMD#44]
之前我也提过建议来改进这个功能，但现在我觉得这个功能确有不妥。下面是我的观点：
1. 开发这个功能是否会导致你承担一定的法律风险？就像刚被抓进去的PanDownload作者一样。
2. 如果这个软件的用户越来越多，是否会在某种程度上损害蓝奏云的利益，致使蓝奏云最终“倒闭”？毕竟相比于没有蓝奏云，不能上传大文件并不重要。
3. 如果一定要保留这个功能，我觉得应该把文件分割/文件改名等功能独立出来，做成一个单独的软件，用户要上传什么文件让用户自己去决定，蓝奏云CMD只负责上传下载相关功能，不要修改用户的文件。这样即使用户上传文件分卷，那也不是你主动提供给用户的功能，而是用户自己将文件分割后上传的。这也可以增加上传大文件的难度，保护蓝奏云。

总结：还是建议直接下架该功能，也不要做什么文件改名/分割的软件，让想上传大文件的人自己去想办法。

**Comment by zaxtyson** [comment]
的确是如此，之前认为分块上传并没有违反蓝奏云的规定，但是 PanDownload 使用 aria2 多线程下载却牵涉到了法律层面的问题(面前这方面的法律很是空缺，主要是损害了运营方的利益)，现在我也不得不考虑这方面的事情。或许 API 可以向 aria2 一样，保留大文件上传的功能，但是做出限制，其它开发者二次开发时需要自行承担法律责任。 CMD 项目仅保留官方的功能，不给普通用户提供直接的支持，防止大量用户涌入损害蓝奏云的利益。

https://github.com/aria2/aria2#disclaimer
