### ISSUE TITLE
登录失败，用户名或密码错误

### ISSUE THREAD

**Issue by zzsnn** [zaxtyson/LanZouCloud-CMD#46]
如题：登录失败，用户名或密码错误，已检查账户密码不存在错误，登录失败

**Comment by DoveBoy** [comment]
同样的问题，尝试改了密码再次登录，问题依旧

**Comment by rachpt** [comment]
登录接口失效，使用cookie登录吧

**Comment by zaxtyson** [comment]
是的，手机版的也加了验证，所以现在得用 cookie 登录了。
课多，再让我先鸽一会（；´д｀)

**Comment by zaxtyson** [comment]
cmd 要模拟改 滑动登录挺麻烦的，现在用 cookie 登录了，见：https://github.com/zaxtyson/LanZouCloud-CMD#v235-%E6%9B%B4%E6%96%B0%E8%AF%B4%E6%98%8E
