### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by leewaro** [zaxtyson/LanZouCloud-CMD#47]
以前的版本超过100m上传会被分卷压缩，想问下载下来怎么打开分卷压缩的文件，显示压缩包被破坏

**Comment by zaxtyson** [comment]
分卷压缩的话，可以用支持 RAR 的解压软件(比如WinRar)打开第一个文件，就能解压了。

**Comment by zaxtyson** [comment]
如果分卷完整(下载的分卷文件序号连续)，压缩包被损坏的话，试一下修复压缩包，之前的版本上传之前都添加了恢复记录的。
