### ISSUE TITLE
希望开发便于分享的有自动下载指定分享文件的子程序

### ISSUE THREAD

**Issue by jzcangshu** [zaxtyson/LanZouCloud-CMD#48]
真是有点不好意思又是我来提要求了...
不过作为一个站长真的不愿意使用百度云盘分享文件，但是让我的所有用户都去下载您的这个程序也不太现实
之前我提出的“点我解压”经过您的说明发现确实过于繁琐
所以又想了一下，来问问能不能帮忙开发如下这样的功能，对于分卷资源分享下载会非常方便，非常感谢！
-----------
在主程序分享时除了分享链接以外增加一个选项：根据所要分享的文件（夹）生成另一个可以独立运行的很小的程序，其中只包含指定被分享文件的链接和下载并解压（意思差不多）的功能（当然加上主程序的链接也可以）。大概就是只要运行这个程序就会列出指定被分享的文件（夹），然后用户确认后即可开始下载分享文件并解压。
每个要被分享给别人下载的文件（夹）都可以用主程序生成这样一个小小的exe，这样分享的时候只需把这个exe发给别人并运行就可以正常下载了
-----------
废话有点多，感谢您能看完，添麻烦了，秋梨膏

**Comment by jzcangshu** [comment]
抱歉，没有看到您已经停止了文件伪装功能，那这条issues可以作废了

**Comment by zaxtyson** [comment]
哈哈，形势所迫。WinRar 可以把大文件变成分卷自解压文件，点exe自动解压，但是分卷后缀.xxx.rar早就被官方杀掉了。所以我们这个分卷方法都是自行设计的，用 python 写一个这样的自解压程序，带上 python 解释器的话，解压程序本身就要 8-9MB，用其它语言写又要考虑跨平台的问题，也挺麻烦的，还可能被喝茶~~
