### ISSUE TITLE
直接下载status显示error

### ISSUE THREAD

**Issue by Chen-Yufeng** [zaxtyson/LanZouCloud-CMD#49]
前两天一直正常使用，今晚直接下载报错，status显示error，疑似API发生改变，重新clone最新版本仍然报错。感谢维护！

**Comment by zaxtyson** [comment]
能给个文件链接嘛，我测试一下。刚刚试了几个文件，通过URL下载或者登录下载大文件，都正常。😁不排除官方那边网页又变化了。

**Comment by Chen-Yufeng** [comment]
感谢回复，我刚刚也测试了几个链接，发现已经恢复正常了，可能是那天晚上突然改变了API（我那天简单分析了貌似是多了一两个参数）。感觉蓝奏云变得有点频繁的样子。

**Comment by Chen-Yufeng** [comment]
开发者你好，我确定了上次的问题是VIP分享的链接导致的，似乎软件不能下载VIP的分享。

**Comment by zaxtyson** [comment]
能分享一下文件的链接嘛，我看看~
蓝奏云官方的的确是变来变去，而且很设计的很凌乱😓

**Comment by Chen-Yufeng** [comment]
emmm我测试的链接不太方便发出来，网上随便找了个类似的，这种分享似乎是VIP专属的：https://www.lanzous.com/b00i9fwj
即使没有那些文件夹，也是显示Error的。这个链接没带密码，不过好像密码验证和普通用户是一样的，因为我是输入了提取码之后显示Error。

还想提一个 Feature request：有些情况下分享链接中某个文件的密码和整个文件夹不同，显示Error，其他文件正常下载了，可以显示那些文件下载失败吗？或者打印到log文件也可以。：）

**Comment by zaxtyson** [comment]
这个界面的确是新的，之前没有这样的，看样子又有事情干了😅
手边还有其它代码要写，蓝奏云这个我会尽快修复的~

**Comment by zaxtyson** [comment]
下载失败的应该有信息，jobs `任务ID` 看一下

**Comment by Chen-Yufeng** [comment]
> 下载失败的应该有信息，jobs `任务ID` 看一下

我没好好读文档otz，刚看到了。

**Comment by zaxtyson** [comment]
`v2.5.7`已经修复vip文件夹的问题，并且支持文件夹递归下载😁

**Comment by Chen-Yufeng** [comment]
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "lanzou\cmder\downloader.py", line 116, in run
  File "lanzou\api\core.py", line 1227, in down_dir_by_url
  File "os.py", line 211, in makedirs
  File "os.py", line 211, in makedirs
  File "os.py", line 221, in makedirs
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\'


~~刚刚测试了下，我的系统没有D盘，安装在E盘里😅~~

setpath之后就好了，以前的版本可以默认下载在安装目录的Download中就没注意orz

**Comment by Chen-Yufeng** [comment]
测试了一下带密码的VIP链接，可以使用了！不过标题中含有`*`的没处理，提了一个PR：）

**Comment by zaxtyson** [comment]
OK，已经merge，我记得之前处理过来着，可能是没处理全吗。蓝奏云这个敏感词暴力过滤就很魔性 😅

之前扔到软件安装路径，有些人找不到下载位置，所以放到D盘了，因为不确定也没有D盘(一般情况都有)所以第一次打开会提醒用户设置保存路径哈哈

**Comment by zaxtyson** [comment]
Windows版已经重新打包~😄

**Comment by Chen-Yufeng** [comment]
存的VIP链接可以开始下载了^_^
