### ISSUE TITLE
在win10X64运行闪退

### ISSUE THREAD

**Issue by cary-rowen** [zaxtyson/LanZouCloud-CMD#5]
执行后闪一下就没了，无论是双击还是cmd中运行。
系统环境：
Windows 版本：Windows 10Ver1909 (64位) build 18363.535
软件版本： lanzou-cmd_v2.2.1

**Comment by zaxtyson** [comment]
ok，了解，目前正在改善回收站功能和修复bug，下一个版本会一次性解决这些问题

**Comment by cary-rowen** [comment]
换了2.3.1，依然会闪退。

**Comment by zaxtyson** [comment]
😱我把系统更新到了你这个版本，但是程序工作正常。请试试在电脑上安装 Python3，然后把项目 clone 下来，在 cmd 里面运行 lanzou-cmd.py， 这样可以看见错误信息😁方便定位bug

**Comment by zaxtyson** [comment]
刚刚在 VirtualBox 中安装了 Windows 10 Ver1909_x64 build 18363.535，该 Bug 没有复现，可能是你那边系统的问题哦🤣~

**Comment by cary-rowen** [comment]
好的，我回头调试下








 ---原始邮件---
发件人: &quot;ZaxTyson&quot;<notifications@github.com&gt;
发送时间: 2020年1月18日(周六) 晚上7:06
收件人: &quot;zaxtyson/LanZouCloud-CMD&quot;<LanZouCloud-CMD@noreply.github.com&gt;;
抄送: &quot;man0528&quot;<603715146@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [zaxtyson/LanZouCloud-CMD] 在win10X64运行闪退 (#5)



刚刚在 VirtualBox 中安装了 Windows 10 Ver1909_x64 build 18363.535，该 Bug 没有复现，可能是你那边系统的问题哦&#x1F923;~
 
&mdash;

**Comment by cary-rowen** [comment]
很抱歉，我不太会python，我克隆了代码到本地，然后运行python lanzou-cmd.py，按照提示安装了"readline"和"lanzou-api"这两个模块，然而运行还是闪退，cmd窗口直接没了，当然在安装"readline"的时候提示我readline在windows系统上不支持，我google搜索，得知需要输入 pip install pyreadline才可以，另外我的python版本是3.8.1。

**Comment by zaxtyson** [comment]
非常抱歉这么久才回复。如果 pip 无法安装`pyreadline`模块，你可以试试手动安装。 请参考：https://stackoverflow.com/questions/14583458/ipython-on-windows-7-cant-find-pyreadline

**Comment by cary-rowen** [comment]
我手动安装了pyreadline2.1，克隆了您最新的提交2.3.2，运行还是闪退，可能是我系统的问题吧！若您想跟踪这个问题我们可以开远程，您在我机器上调试。

**Comment by zaxtyson** [comment]
可以的，信息请发到邮箱：zaxtyson@foxmail.com😁

**Comment by cary-rowen** [comment]
实在抱歉浪费了您不少时间，问题查出来了，是因为我使用的另一款软件而导致的软件崩溃。再次感谢您的耐心解答！
