### ISSUE TITLE
关于上传文件问题

### ISSUE THREAD

**Issue by dada8686** [zaxtyson/LanZouCloud-CMD#50]
批量上传非常方便，感谢作者，上传非常小的文件会不显示上传状态，你的教程里面有上传状态，有状态还是很方便观察的
顺便问下，作者有建交流群吗

**Comment by zaxtyson** [comment]
上传小文件也是会在jobs里面显示的，我试了一下创建了一个文本文档，随便写了两个字。

![](https://upload.cc/i1/2020/06/01/BGx67k.png)

**Comment by zaxtyson** [comment]
交流群是没有的，猥琐发育。PD作者已经进去了。

**Comment by dada8686** [comment]
是的 ，搞一个私密群用来反馈问题？
用服务器上传大批量文件不会失效一个，用个人电脑上传1000个文件能成功800多个，官方是一次上传20个文件秒上传，我们这个是后台服务器一个一个上传吗？不好改善吧？
批量上传的功能还是不错的，是一个亮点，可以提升速度，那就更好了
![image](https://user-images.githubusercontent.com/56195327/83481629-e4fa8e80-a4d0-11ea-80a9-a869fe39d7a9.png)

![image](https://user-images.githubusercontent.com/56195327/83483098-761f3480-a4d4-11ea-9442-6c88e04236be.png)

第一个上传失败，不清楚是传完了还是有几个失败的，几乎所有的都是这样，下面的1，2文件夹是同时上传，不清楚最多支持多少的文件夹同时上传

**Comment by zaxtyson** [comment]
官方上传文件都是排队一个一个上传的。我们这个可以同时上传多个文件，我也不知道会发生什么（要看官方后台怎么处理了），上传失败是可能的，所以尽可能不要一次性提交多个上传任务。如果有很多小文件的话，打包压缩上传更快一些。

**Comment by dada8686** [comment]
好的 ，感谢作者，目前得知大概率上传100丢20左右，还是很方便的，一个一个上传是方便了下载

**Comment by dada8686** [comment]
![image](https://user-images.githubusercontent.com/56195327/83965639-9c374100-a8e7-11ea-9bfd-46a4ba7ec8fc.png)
请问作者，像这种批量文件的分享链接，可以用导出的方式为txt或者excel格式吗？还有这种窗口不能翻页就很不方便了😅或者这个功能不好解决？后期会加上不，期待！😀

**Comment by zaxtyson** [comment]
（＞人＜；）暑假再整。

这个是Windows终端的问题，之前为了好看点把窗口高度设置的比较小，但是缓冲区也是跟着变了。可以右键CMD的窗口，在属性里面设置CMD窗口的缓冲区大小。

**Comment by dada8686** [comment]
期待！

**Comment by zaxtyson** [comment]
`v2.5.2`已经支持导出文件夹下的文件到CSV文件，后期可以使用excel等软件去处理😁

**Comment by dada8686** [comment]
好嘞，作者辛苦了，方便提供下 ”export  导出文件夹下的文件信息到CSV文件“导出目录或者使用教程，有点小白不懂，我直接export xxx  然后说 [Errno 2] No such file or directory: './Download\\2020-07-18_11-01-01.csv' 没有这个目录，不懂要导出到哪里，麻烦作者了😂

**Comment by zaxtyson** [comment]
导出位置就是下载路径。默认下载路径是程序安装路径下的Download文件夹，可以右键桌面图标，打开文件位置找到。默认下载路径使用setpath命令修改。😁最好改一下默认路径，方便找。

**Comment by dada8686** [comment]
好的，十分感谢作者的解答，可能我装软件有问题，在软件目录一直没有Download（可能没有权限新建吧），切换下载路径后一点问题都没有，真的很方便，作者太棒了！！！

**Comment by dada8686** [comment]
作者这个意思是 搞不下来了吗？ 
Error : 'gbk' codec can't encode character '\u2022' in position 24: illegal multibyte sequence
![image](https://user-images.githubusercontent.com/56195327/88156627-41aa3800-cc3c-11ea-9455-ddc66aca2353.png)
错误还是很多的，原因的文件名称中有特殊符号，这个可以避免吧？直接跳过这个文件或者特殊符号不编码等等，希望可以得到解决！

**Comment by zaxtyson** [comment]
可能是保存时的编码问题，Windows自动转GBK编码了，而且你文件名出现了一些GBK编码不支持的字符。没办法测试我就只能猜测了。

刚刚创建了一个分支，下载[这个](https://github.com/zaxtyson/LanZouCloud-CMD/archive/fix_export.zip)，没有打包成exe文件，电脑需要安装python3.8，点击 `lanzou_cmd.py` 即可运行，看看能不能解决问题。

**Comment by dada8686** [comment]
抱歉作者，不知道啥原因，这个文件打不开。

Traceback (most recent call last):
  File "E:\Desktop\新建文件夹\lanzou_cmd.py", line 1, in <module>
    from lanzou.cmder.cmder import Commander
  File "E:\Desktop\新建文件夹\lanzou\cmder\cmder.py", line 159
    elif folder := self._dir_list.find_by_name(dir_name):
                 ^
SyntaxError: invalid syntax

Windows 10 x64

**Comment by zaxtyson** [comment]
python版本过低，这里用了 python3.8的特性，低版本直接爆语法错误

**Comment by dada8686** [comment]
我自己测试了一下，python3.8.5，双击打不开，我的那位朋友也是打不开，不清楚他的版本号。如果作者方便的话，我想我们应该tg（电报）交谈，我的账号：@Ww_OooO,我来帮助你测试bug，因为用的比较频繁，几乎每天都在用。

**Comment by zaxtyson** [comment]
ok，tg号同github @zaxtyson
发了信息，不知道你那边看到没有😀

**Comment by dada8686** [comment]
作者，还有一个小小的问题，文件夹下的文件夹不能导出链接，也是不常用的。哈哈哈
