### ISSUE TITLE
文件批量分享

### ISSUE THREAD

**Issue by hnlyj** [zaxtyson/LanZouCloud-CMD#51]
大神能否开发一个批量生成 文件命+链接格式的功能  能导出来

**Comment by zaxtyson** [comment]
遍历导出整个文件夹的内容吗，可以是可以，我先鸽一段时间(/▽＼)

**Comment by hnlyj** [comment]
好的，谢谢啦，做推广挨个点击右面多------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ZaxTyson&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月10日(星期三) 晚上10:04
收件人:&nbsp;&quot;zaxtyson/LanZouCloud-CMD&quot;<LanZouCloud-CMD@noreply.github.com&gt;;
抄送:&nbsp;&quot;hnlyj&quot;<532268865@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zaxtyson/LanZouCloud-CMD] 文件批量分享 (#51)

**Comment by zaxtyson** [comment]
`v2.5.2`已经支持导出文件夹下的文件到CSV文件，后期可以使用excel等软件去处理

**Comment by hnlyj** [comment]
非常感谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZaxTyson"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 晚上9:51
收件人: "zaxtyson/LanZouCloud-CMD"<LanZouCloud-CMD@noreply.github.com&gt;; 
抄送: "梁宇靖"<532268865@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zaxtyson/LanZouCloud-CMD] 文件批量分享 (#51)





 
v2.5.2已经支持导出文件夹下的文件到CSV文件，后期可以使用excel等软件去处理
