### ISSUE TITLE
怎么上传文件？ Wiki里面并没有演示啊

### ISSUE THREAD

**Issue by hl668** [zaxtyson/LanZouCloud-CMD#6]
作者你好，我看了下Wiki，上传文件那里并没有演示如何上传。请问怎么上传文件？上传文件是从电脑哪个目录获取文件并上传的？

**Comment by zaxtyson** [comment]
上传文件请使用 `upload` 命令，命令后的参数是文件或者文件夹的路径，比如说 `upload D:\test\1.mp4` 。在 Windows 下，您可以直接将文件拖入 CMD 窗口，会自动输入文件的路径。
