### ISSUE TITLE
上传windows系统时丢失了一些卷

### ISSUE THREAD

**Issue by srcrs** [zaxtyson/LanZouCloud-CMD#7]
本来应该改分成40卷左右，但是前面十卷丢失，也就是直接从第10卷开始上传。测试发现是命名错误，前十卷和后面三十卷命名不一样。

**Comment by srcrs** [comment]
LanZouCloud > upload E:\GHO\Windows7_64_201810.iso
44.66% [>>>>>>>>>>>>>=====================] 44.7/100.0MB | Windows7_201810.wtf10.rar

**Comment by srcrs** [comment]
原本应该从1开始的，但是丢失掉了，直接从10开始

**Comment by srcrs** [comment]
Windows7_64_201810.part01.rar
Windows7_64_201810.part02.rar
应该是只要超过1G的文件就会出错

**Comment by srcrs** [comment]
API项目中
是不是
cmd_args = f'a -m{rar_level} -v{self._max_size}m -ep -y -rr5% "./tmp/{file_name}" "{file_path}"'
在这里01没有匹配到的问题？

**Comment by zaxtyson** [comment]
感谢反馈，bug出现在 `file_list = [f"{file_name}.part{i}.rar" for i in range(1, part_sum + 1)]`，rar 分段文件数量超过10，就会以 `.part0X.rar` 命名，而程序这里忽视了补齐的 0

**Comment by srcrs** [comment]
是的，应该好解决吧

**Comment by zaxtyson** [comment]
api 已经修复(￣▽￣)" ，CMD马上搞定

**Comment by zaxtyson** [comment]
OK~~

**Comment by srcrs** [comment]
不行，现在上传超过100m闪退

**Comment by zaxtyson** [comment]
之前打包出了点问题，你重新下载试试，已经替换了

**Comment by srcrs** [comment]
可以了
