### ISSUE TITLE
文件显示的时间是今天而不是真实的上传时间

### ISSUE THREAD

**Issue by ghost** [zaxtyson/LanZouCloud-CMD#8]

**Comment by ghost** [comment]
还有就是 "cd /" 不能返回主目录

**Comment by ghost** [comment]
还有一个 自动补全只能补全文件名，不能补全命令

**Comment by ghost** [comment]
文件夹的名称对不齐，有些文件夹会向左缩进

**Comment by ghost** [comment]
如果能把描述放后面会不会好一些，这样就算对不齐也是描述对不齐

**Comment by ghost** [comment]
对不齐可能和描述有关，而且没有描述的文件夹前面会空空的，比较奇怪
建议把描述放后面，把文件夹名称放前面

**Comment by zaxtyson** [comment]
描述信息会只显示一部分，但是文件(夹)长度不固定，所以放在最后。不对齐应该是 cmd 下面中文空格和英文空格字符宽度不一致的问题，描述为空的时候，填充的是中文空格，有描述时用英文补全的，描述如果全英文或者是带中文，字符宽度又不一样，挺麻烦的😂。

**Comment by ghost** [comment]
还有个小问题，如果我下载的是文件夹，下载的时候会下载文件夹里面的文件，而不是在本地新建一个同名文件夹，然后下载到这个文件夹里面，这个可能和分卷上传下载功能冲突了吧？如果实在不好解决，能否加一个“每次下载的时候选择下载位置/使用上次的下载位置”的功能

**Comment by srcrs** [comment]
这个是支持选择下载的位置的，默认有一个下载的位置，可以修改。默认下载路径.\lanzou-cmd\Download。

**Comment by ghost** [comment]
我的意思是，我想下载一个文件夹，下载之后他还是一个文件夹，但是现在的情况是下载之后他是一堆文件

**Comment by zaxtyson** [comment]
下载文件夹自动在本地创建文件夹，这个的确应该加上

**Comment by zaxtyson** [comment]
😂刚刚提交的更新，再合并一次

**Comment by zaxtyson** [comment]
`v2.3.4` 已经修复全部问题😁
