### ISSUE TITLE
蓝奏云有会员功能，有没有考虑一下先检测一下用户上传文件的限制等级，超过等级限制大小的再分段

### ISSUE THREAD

**Issue by simonbntt** [zaxtyson/LanZouCloud-CMD#9]
蓝奏云有会员功能，有没有考虑一下先检测一下用户上传文件的限制等级，超过等级限制大小的再分段

**Comment by simonbntt** [comment]
因为我开的是大文件特权，所以超过100m的文件我可以直接上传，但是用软件的话就得分段，不想分段就不行了，这个地方最好修改一下，先判断用户上传大小限制是什么等级，超出了上传限制再分割

**Comment by simonbntt** [comment]
而且官网写的那个文件等级也是不对的，官网V1是110mV2是160mV3是210，我开的V3，实际限制260M，所以如果加判断上传限制的功能最好不是写死了，能实时检测一下

**Comment by simonbntt** [comment]
希望这个功能早日更新出来，省得我一个一个上传，爱你mua

**Comment by zaxtyson** [comment]
之前没有考虑会员的情况，因为我也是免费用户😝，所以不知道会员是什么情况，下一个版本会加上。另外，会员可以修改文件名，这个之前也没设置，之后加上。

**Comment by zaxtyson** [comment]
`v2.3.4`已经支持 `setsize` 命令修改分卷大小, 支持 `rename` 修改文件名~
